// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "HW5.hpp"

Fl_Output *gameOutput=(Fl_Output *)0;

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(600, 400);
    w = o; if (w) {/* empty */}
    { Fl_Tile* o = new Fl_Tile(20, 25, 360, 360);
      o->box(FL_BORDER_BOX);
      o->color((Fl_Color)1);
      o->align(Fl_Align(129));
      { Fl_Button* o = new Fl_Button(20, 70, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
        o->labelcolor((Fl_Color)1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(335, 25, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
        o->labelcolor((Fl_Color)1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(335, 115, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
        o->labelcolor((Fl_Color)1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(290, 70, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
        o->labelcolor((Fl_Color)1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(245, 25, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
        o->labelcolor((Fl_Color)1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(245, 115, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
        o->labelcolor((Fl_Color)1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(200, 70, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
        o->labelcolor((Fl_Color)1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(155, 115, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
        o->labelcolor((Fl_Color)1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(110, 70, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
        o->labelcolor((Fl_Color)1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(155, 25, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
        o->labelcolor((Fl_Color)1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(65, 115, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
        o->labelcolor((Fl_Color)1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(65, 25, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
        o->labelcolor((Fl_Color)1);
        o->callback((Fl_Callback*)Output_Hello);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(20, 160, 45, 45);
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(335, 205, 45, 45);
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(245, 205, 45, 45);
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(155, 205, 45, 45);
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(65, 205, 45, 45);
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(290, 160, 45, 45);
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(200, 160, 45, 45);
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(110, 160, 45, 45);
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(110, 340, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(155, 295, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(200, 340, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(335, 295, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(290, 340, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(245, 295, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(110, 250, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(200, 250, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(290, 250, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(65, 295, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(20, 250, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(20, 340, 45, 45, "@circle");
        o->box(FL_FLAT_BOX);
        o->color(FL_FOREGROUND_COLOR);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelsize(19);
      } // Fl_Button* o
      o->end();
    } // Fl_Tile* o
    { gameOutput = new Fl_Output(440, 27, 150, 46, "output:");
    } // Fl_Output* gameOutput
    o->end();
  } // Fl_Double_Window* o
  checkerboard gameBoard;
  gameBoard.setupBoard();
  w->show(argc, argv);
  return Fl::run();
}

void Output_Hello(Fl_Widget*, void*) {
  gameOutput->value(gameBoard.displayBoard());
}
